config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants, only: %i[index new create show] do
    # # Read all
    # get 'restaurants', to: 'restaurants#index', as: :restaurants

    # # Create one
    # get 'restaurants/new', to: 'restaurants#new', as: :new_restaurant
    # post 'restaurants', to: 'restaurants#create'

    # # Read one - show must go after the "new" routes
    # get 'restaurants/:id', to: 'restaurants#show', as: :restaurant

    collection do
      get 'italian'
    end
    # es como agregar
    # get 'restaurants/italian', to: "restaurants#italian", as: :italian_restaurants

    member do
      get 'chef'
    end
    # este va a generar la ruta pero con un id
    # get 'restaurants/:id/chef', to: "restaurants#chef", as: :chef_restaurants

    # Nested routes
    resources :reviews, only: %i[new create]

    # collection top
    collection do
      get 'top'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  # validations:
  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true
  validates :category, inclusion: { in: %w[chinese italian japanese french belgian] }

  # after_find :average_rating
  def average_rating
    self.average_rating = (reviews.sum(&:rating).to_f / reviews.count)
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, presence: true
  validates :rating, numericality: true
  validates :rating, inclusion: { in: (0..5).to_a }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :chef]

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def italian
    @restaurants = Restaurant.where(category: 'italian')
  end

  def chef
  end

  def top
    # @top_restaurants = Restaurant.where('average_rating > ?', 2).order(average_rating: :desc)
    @top_restaurants = Restaurant.order(average_rating: :desc).limit(5)
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category, :chef_name)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: [:new, :create, :top]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
  def star_rating(rating)
    counter = 0
    stars = ""
    5.times do
      stars += "<i class='fa #{rating > counter ? 'fa-star' : 'fa-star-o'}'></i>"
      counter += 1
    end
    stars
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
  def star_rating(rating)
    counter = 0
    stars = ""
    5.times do
      stars += "<i class='fa #{rating > counter ? 'fa-star' : 'fa-star-o'}'></i>"
      counter += 1
    end
    stars
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RestaurantMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category %>
  <%= f.button :submit, class: 'btn btn-outline-info' %>
<% end %>

app/views/restaurants/chef.html.erb
<div class="container col-8 py-3">
  <div class="d-flex justify-content-start aling-items-center">
    <h2 class="text-info my-0 mr-2"><%= @restaurant.name %></h2>
    <p>El chef de <%= @restaurant.name %> es <%= @restaurant.chef_name %>.</p>
  </div>
  <div class="container border border-light my-3"></div>
  <%= link_to 'Back', restaurant_path(@restaurant), :class => "btn btn-outline-info mt-2"  %>
</div>

app/views/restaurants/index.html.erb
<div class="container col-8 py-3">
  <h1 class="my-3 font-weight-bolder text-info">Restaurants</h1>
  <div class="container border border-secondary my-3"></div>
  <h2><%= link_to "Italian Restaurants", italian_restaurants_path, :class => "text-info"  %></h2>
  <h2><%= link_to "Top Restaurants", top_restaurants_path, :class => "text-info"  %></h2>
  <div class="container border border-secondary my-3"></div>
  <%= link_to new_restaurant_path do %>
    <i class="fas fa-plus"></i> Add a new restaurant
  <% end %>
  <div class="container border border-secondary my-3"></div>
  <% @restaurants.each do |restaurant| %>
    <h2><%= link_to restaurant.name, restaurant_path(restaurant), :class => "text-info"  %></h2>
    <p><%= restaurant.address %></p>
  <% end %>
</div>

app/views/restaurants/italian.html.erb
<div class="container col-8 py-3">
  <h1 class="my-3 font-weight-bolder text-info">Best Restaurants</h1>
  <div class="container border border-secondary my-3"></div>
  <% @restaurants.each do |restaurant| %>
    <h2><%= link_to restaurant.name, restaurant_path(restaurant), :class => "text-info"  %></h2>
    <p><%= restaurant.category %></p>
  <% end %>
  <%= link_to 'Back to main list', restaurants_path, :class => "btn btn-outline-info mt-2"  %>
</div>

app/views/restaurants/new.html.erb
<div class="container">
  <h1 class="my-3 font-weight-bolder text-info">New Restaurant</h1>
  <%= render "form", restaurant: @restaurant %>
  <%= link_to 'Back', restaurants_path, :class => "btn btn-outline-info mt-2"  %>
</div>

app/views/restaurants/show.html.erb
<div class="container col-8 py-3">
  <div class="d-flex justify-content-start aling-items-center">
    <h2 class="text-info my-0 mr-2"><%= @restaurant.name %></h2>
  </div>
  <div class="container border border-light my-3"></div>
  <p><%= @restaurant.address %></p>
  <%= link_to 'Show chef', chef_restaurant_path(@restaurant), :class => "btn btn-outline-info mt-2"  %>
  <%= link_to 'Back', restaurants_path, :class => "btn btn-outline-info mt-2"  %>
  <div class="container border border-light my-3"></div>
  <%= link_to 'Review this restaurant', new_restaurant_review_path(@restaurant), :class => "btn btn-outline-info mt-2"  %>
  <div class="container border border-light my-3"></div>
  <h2>Reviews</h2>
  <% @restaurant.reviews.each do |review| %>
    <p><%= review.content %></p>
    <p><%= sanitize star_rating(review.rating) %></p>
  <% end %>
</div>

app/views/restaurants/top.html.erb
<div class="container col-8 py-3">
  <h1 class="my-3 font-weight-bolder text-info">Top 5 Restaurants</h1>
  <div class="container border border-secondary my-3"></div>
  <% @top_restaurants.each do |restaurant| %>
    <h2><%= link_to restaurant.name, restaurant_path(restaurant), :class => "text-info"  %></h2>
    <p>Address: <%= restaurant.address %></p>
    <p>Average rating: <%= sanitize star_rating(restaurant.average_rating) %></p>
    <p><strong>Latest Reviews</strong></p>
    <% restaurant.reviews.first(3).each do |review| %>
      <p><em><%= Date.today.strftime("%d/%m/%y") %></em>: <%= review.content %></p>
    <% end %>

  <% end %>
  <%= link_to 'Back to main list', restaurants_path, :class => "btn btn-outline-info mt-2"  %>
</div>

app/views/reviews/new.html.erb
<div class="container">
  <h1 class="my-3 font-weight-bolder text-info">New Review for <%= @restaurant.name %></h1>
  <%= simple_form_for [@restaurant, @review] do |f| %>
    <%= f.input :content %>
    <%= f.input :rating %>
    <%= f.button :submit, class: 'btn btn-outline-info' %>
  <% end %>
  <%= link_to 'Back', restaurants_path, :class => "btn btn-outline-info mt-2"  %>
</div>